#!/usr/bin/env bash
# Regenerate the pinned wheel list the Flatpak build installs from.
#
# flatpak-builder runs module builds with no network, so every wheel has to be
# declared up front as a source with a checksum. Resolution is pinned to the
# Python the Flatpak runtime ships rather than whatever python happens to be on
# this machine, so the wheels match the sandbox and not the developer: several
# of these dependencies carry compiled extensions and are ABI-specific.
#
# Re-run after changing helper/requirements.txt, or after moving to a runtime
# with a different Python, and commit the result.
set -euo pipefail
root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
out="$root/packaging/flatpak/python3-deps.yml"

# Must match the interpreter in the runtime the manifest pins.
python_version="${SUNG_FLATPAK_PYTHON:-3.13}"
abi="cp${python_version//./}"

work="$(mktemp -d)"
trap 'rm -rf -- "$work"' EXIT

python3 -m pip install --dry-run --quiet --report "$work/report.json" \
  --only-binary=:all: \
  --python-version "$python_version" --abi "$abi" \
  --platform manylinux_2_28_x86_64 \
  --platform manylinux2014_x86_64 \
  --platform any \
  --target "$work/unused" \
  -r "$root/helper/requirements.txt"

python3 - "$work/report.json" "$out" "$python_version" <<'PY'
import json, sys

report, out, python_version = sys.argv[1], sys.argv[2], sys.argv[3]
entries = []
for item in json.load(open(report))["install"]:
    info = item["download_info"]
    sha = info.get("archive_info", {}).get("hashes", {}).get("sha256")
    if not sha:
        raise SystemExit(f"no sha256 for {info['url']}")
    entries.append((info["url"].rsplit("/", 1)[-1], info["url"], sha))
entries.sort()

lines = [
    "# Generated by packaging/flatpak/generate-python-sources.sh -- do not edit.",
    f"# Wheels resolved for the runtime's Python {python_version}.",
    "name: python3-deps",
    "buildsystem: simple",
    "build-commands:",
    "  - python3 -m pip install --no-index --no-deps --no-compile",
    "      --target=/app/lib/sung/python *.whl",
    "sources:",
]
for name, url, sha in entries:
    lines += [f"  # {name}", "  - type: file", f"    url: {url}", f"    sha256: {sha}"]

with open(out, "w") as handle:
    handle.write("\n".join(lines) + "\n")
print(f"wrote {out} with {len(entries)} wheels")
PY
